### ISSUE TITLE
NgxPermissionsGuard: route without data.permissions

### ISSUE THREAD

**Issue by AlexWalkerson** [AlexKhymenko/ngx-permissions#148]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

```
Error: Uncaught (in promise): TypeError: Cannot read property 'only' of undefined
TypeError: Cannot read property 'only' of undefined
at NgxPermissionsGuard.transformPermission 
```

## Expected behavior
NgxPermissionsGuard should ignore routes that do not have data.permission property.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ivy-dx9cyu
root - OK
child-component - OK
grand child-component - ERROR

## Solution
Check whether the route has the "permission" property
[permissions-guard.service.ts](https://github.com/AlexKhymenko/ngx-permissions/blob/a8ba73a73cfc84801a86c3d2099fe0a3cbcafcf8/projects/ngx-permissions/src/lib/router/permissions-guard.service.ts#L56)
```ts
const routeDataPermissions = !!route && route.data && route.data.permissions ? (route.data.permissions as NgxPermissionsRouterData) : {};
```

## Environment

<pre><code>
Angular version: 10.1.1
ngx-permissions version: 8.0.0

Browser:
- [ x] Chrome (desktop) version 85
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by AlexWalkerson** [comment]
Are there any changes regarding this issue?
![image](https://user-images.githubusercontent.com/16510166/94692571-5b9e8000-033b-11eb-8b57-89c54f7d66a2.png)

**Comment by AlexKhymenko** [comment]
Hi @AlexWalkerson Thank For patience. So basically to fix it there is a need to specify data in child component . This is angular restriction
![image](https://user-images.githubusercontent.com/6598397/94777569-563d4600-03cc-11eb-83a9-859f691f2d58.png)

In wiki there is description https://github.com/AlexKhymenko/ngx-permissions/wiki/Usage-with-routes#can-activate-child-guard


Working example here https://stackblitz.com/edit/angular-ivy-ming6q?file=src%2Fapp%2Fapp-routing.module.ts

**Comment by MykhailoIskiv** [comment]
Hi @AlexKhymenko, thanks for the lib :)
I'm facing the same issue, during update the lib from 7.0.3 to 8.1.0.
After updating it I got the error as originally described by @AlexWalkerson.
I have a ```canActivateChild: [NgxPermissionsGuard]``` in my parent route
and in my child routes I have
```
data: {
    permissions: {
        only: ['SOME_ROLE'],
        redirectTo: someFunctionThatExecuteRedirectLogic
    }
}
```

but I need to run guard  only for some of my child routes, not all
so
previously I was able to add canActivateChild guard to parent and add permissions data only to the routes that I want to check and it worked.
In version 8.1.0 I can't do that, as I have to rewrite canActivateChild logic for my routes to ```canActivate: [NgxPermissionsGuard]``` and data with permissions to each router I want to check or use ```canActivateChild: [NgxPermissionsGuard]``` and add permissions data to routes that I don't need to check.
Currently it fails due to this line of code
https://github.com/AlexKhymenko/ngx-permissions/blob/master/projects/ngx-permissions/src/lib/router/permissions-guard.service.ts#L56

```const routeDataPermissions = !!route && route.data ? (route.data.permissions as NgxPermissionsRouterData) : {};```
as it assumes that if it has data then it has permissions property on it, but it's not always true, as described above.
Don't you think it would be good to change it to 
```
const routeDataPermissions = !!route && route.data && route.data.permissions? (route.data.permissions as NgxPermissionsRouterData) : {}; 
``` 
or 
```
const routeDataPermissions = !!route?.data?.permissions ? (route.data.permissions as NgxPermissionsRouterData) : {};
```
to fix the issue?
It would allow to add canActivateChild to parent and and would not require to add permissions to routes that doesn't need check
